version: "3.9"

services:

  hub:
    container_name: hub
    build: ./hub 
    depends_on: 
      - alpine
      - mongo
      - mongo-express

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: on-failure
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    volumes: 
      - mongodb:/data/db
    
  
  alpine: #backup for mongo
    container_name: alpine 
    build: ./alpine
    environment:
      URI: mongodb://root:example@mongo:27017/?authSource=admin
      BACKUP_PATH: /var/opt/backups/
    volumes: 
      - ./alpine/backups:/var/opt/backups
      -  mongodb:/data/db


  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes: 
  mongodb:
    