version: "3.9"

services:

  hub:
    container_name: hub
    build: ./hub 
    depends_on: 
      - alpine
      - mongo
      - mongo-express

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: on-failure
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - mongodb:/data/db
    
  
  alpine: #backup for mongo
    container_name: alpine 
    build: ./alpine
    restart: on-failure
    volumes: 
      - ./alpine/startup.sh:/usr/local/bin/startup.sh:ro
      - ./alpine/6hour:/etc/periodic/6hour/:ro
      - ./alpine/backups:/var/opt/backups
      -  mongodb:/data/db


  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes: 
  mongodb:
    